import { Tool, ToolCategory } from '../types';

export type { ToolCategory };

export const iconMap: Record<string, string> = {
  FileText: '📄',
  FileUp: '📝',
  Image: '🖼️',
  FilePlus: '📋',
  ImagePlus: '🖼️',
  FilePlus2: '📋',
  Table: '📊',
  Monitor: '📽️',
  GitMerge: '🔗',
  Scissors: '✂️',
  ArrowDownToLine: '📦',
  RotateCw: '🔄',
  LayoutGrid: '📐',
  Trash2: '🗑️',
  Copy: '📑',
};

export const tools: Tool[] = [
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    shortName: 'PDF → Word',
    description: 'Convert PDF files to editable Word documents with high accuracy.',
    longDescription: 'Transform your static PDF documents into fully editable Word files. Our advanced conversion engine preserves formatting, tables, images, and text layout with exceptional accuracy.',
    category: 'convert',
    iconName: 'FileText',
    gradient: 'from-blue-500 to-cyan-500',
    inputFormat: 'PDF',
    outputFormat: 'DOCX',
    popular: true,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Our engine converts it to Word', 'Download your editable DOCX'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    shortName: 'Word → PDF',
    description: 'Convert Word documents to PDF format while preserving layout.',
    longDescription: 'Easily convert your Word documents to universally compatible PDF files. Perfect formatting preservation ensures your documents look identical across all devices and platforms.',
    category: 'convert',
    iconName: 'FileUp',
    gradient: 'from-cyan-500 to-blue-500',
    inputFormat: 'DOCX',
    outputFormat: 'PDF',
    popular: true,
    acceptTypes: '.doc,.docx',
    multiple: false,
    steps: ['Upload your Word document', 'Click convert to PDF', 'Download your PDF file'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    shortName: 'PDF → JPG',
    description: 'Convert each page of your PDF into high-quality JPG images.',
    longDescription: 'Extract every page from your PDF as high-resolution JPG images. Ideal for presentations, web publishing, or when you need individual page images from your document.',
    category: 'convert',
    iconName: 'Image',
    gradient: 'from-orange-500 to-amber-500',
    inputFormat: 'PDF',
    outputFormat: 'JPG',
    popular: true,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Each page converts to JPG', 'Download your images'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    shortName: 'JPG → PDF',
    description: 'Convert JPG images to a single PDF document.',
    longDescription: 'Combine multiple JPG images into a single, well-organized PDF document. Perfect for creating photo albums, reports, or compiling scanned documents.',
    category: 'convert',
    iconName: 'FilePlus',
    gradient: 'from-amber-500 to-orange-500',
    inputFormat: 'JPG',
    outputFormat: 'PDF',
    popular: true,
    acceptTypes: '.jpg,.jpeg',
    multiple: true,
    steps: ['Upload your JPG images', 'Arrange them in order', 'Download your PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    name: 'PDF to PNG',
    shortName: 'PDF → PNG',
    description: 'Convert PDF pages to transparent PNG images.',
    longDescription: 'Convert your PDF pages into high-quality PNG images with transparency support. Great for graphic design, web content, and high-fidelity image extraction.',
    category: 'convert',
    iconName: 'ImagePlus',
    gradient: 'from-pink-500 to-rose-500',
    inputFormat: 'PDF',
    outputFormat: 'PNG',
    popular: false,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Each page converts to PNG', 'Download your images'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    name: 'PNG to PDF',
    shortName: 'PNG → PDF',
    description: 'Convert PNG images to a professional PDF document.',
    longDescription: 'Transform your PNG images into a clean, professional PDF document. Supports multiple images and maintains the original quality and transparency.',
    category: 'convert',
    iconName: 'FilePlus2',
    gradient: 'from-rose-500 to-pink-500',
    inputFormat: 'PNG',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.png',
    multiple: true,
    steps: ['Upload your PNG images', 'Arrange them in order', 'Download your PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    shortName: 'Excel → PDF',
    description: 'Convert Excel spreadsheets to clean PDF documents.',
    longDescription: 'Convert your Excel spreadsheets into perfectly formatted PDF documents. Preserves table structures, charts, and data formatting for professional sharing.',
    category: 'convert',
    iconName: 'Table',
    gradient: 'from-emerald-500 to-green-500',
    inputFormat: 'XLSX',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.xls,.xlsx',
    multiple: false,
    steps: ['Upload your Excel file', 'Click convert to PDF', 'Download your PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    shortName: 'PPT → PDF',
    description: 'Convert PowerPoint presentations to PDF format.',
    longDescription: 'Transform your PowerPoint presentations into shareable PDF files. Preserves slide layouts, images, and formatting for universal compatibility.',
    category: 'convert',
    iconName: 'Monitor',
    gradient: 'from-red-500 to-orange-500',
    inputFormat: 'PPTX',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.ppt,.pptx',
    multiple: false,
    steps: ['Upload your PowerPoint file', 'Click convert to PDF', 'Download your PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    shortName: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document.',
    longDescription: 'Seamlessly merge multiple PDF files into one unified document. Drag and drop to reorder, then combine them instantly. Perfect for compiling reports and presentations.',
    category: 'organize',
    iconName: 'GitMerge',
    gradient: 'from-violet-500 to-purple-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: true,
    acceptTypes: '.pdf',
    multiple: true,
    steps: ['Upload multiple PDF files', 'Drag to reorder them', 'Download your merged PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Split PDF',
    shortName: 'Split PDF',
    description: 'Split a PDF into separate documents by page ranges.',
    longDescription: 'Divide your PDF into multiple smaller documents. Choose specific page ranges or split at every page — full control over how your document is separated.',
    category: 'organize',
    iconName: 'Scissors',
    gradient: 'from-purple-500 to-violet-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: true,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Choose split points or ranges', 'Download your separate PDFs'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    shortName: 'Compress',
    description: 'Reduce PDF file size while maintaining quality.',
    longDescription: 'Significantly reduce your PDF file size without compromising visual quality. Choose from different compression levels to balance size and quality for your needs.',
    category: 'optimize',
    iconName: 'ArrowDownToLine',
    gradient: 'from-emerald-500 to-teal-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: true,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Choose compression level', 'Download your compressed PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    shortName: 'Rotate',
    description: 'Rotate PDF pages to the correct orientation.',
    longDescription: 'Quickly rotate individual pages or entire PDF documents to the correct orientation. Support for 90°, 180°, and 270° rotations with instant preview.',
    category: 'organize',
    iconName: 'RotateCw',
    gradient: 'from-indigo-500 to-blue-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Select rotation angle', 'Download your rotated PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'organize-pages',
    slug: 'organize-pages',
    name: 'Organize Pages',
    shortName: 'Organize',
    description: 'Reorder, rotate, and rearrange PDF pages visually.',
    longDescription: 'Take full control of your PDF page order. Drag and drop pages to reorder, rotate individual pages, and organize your document exactly how you need it.',
    category: 'organize',
    iconName: 'LayoutGrid',
    gradient: 'from-fuchsia-500 to-pink-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Drag pages to reorder', 'Download your organized PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'delete-pages',
    slug: 'delete-pages',
    name: 'Delete Pages',
    shortName: 'Delete',
    description: 'Remove unwanted pages from your PDF document.',
    longDescription: 'Easily remove specific pages from your PDF document. Select the pages you no longer need and delete them instantly while keeping the rest intact.',
    category: 'organize',
    iconName: 'Trash2',
    gradient: 'from-red-500 to-rose-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Select pages to delete', 'Download your trimmed PDF'],
    clientSide: true,
    comingSoon: false,
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    shortName: 'Extract',
    description: 'Extract specific pages from a PDF into a new document.',
    longDescription: 'Extract selected pages from your PDF into a new, separate document. Perfect for sharing specific sections without sending the entire file.',
    category: 'organize',
    iconName: 'Copy',
    gradient: 'from-teal-500 to-cyan-500',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    popular: false,
    acceptTypes: '.pdf',
    multiple: false,
    steps: ['Upload your PDF file', 'Select pages to extract', 'Download your new PDF'],
    clientSide: true,
    comingSoon: false,
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(t => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter(t => t.category === category);
}

export function getPopularTools(): Tool[] {
  return tools.filter(t => t.popular);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim();
  if (!q) return tools;
  return tools.filter(
    t =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.inputFormat.toLowerCase().includes(q) ||
      t.outputFormat.toLowerCase().includes(q)
  );
}

export const categoryLabels: Record<ToolCategory, string> = {
  convert: 'Convert',
  optimize: 'Optimize',
  organize: 'Organize',
};

export const categoryDescriptions: Record<ToolCategory, string> = {
  convert: 'Transform your documents between formats',
  optimize: 'Reduce size and improve quality',
  organize: 'Rearrange, split, and manage pages',
};
